routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index')->middleware('verified');


Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('refLevels', 'RefLevelController');

Route::resource('refCategories', 'RefCategoryController');

app/Models/RefLevel.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class RefLevel
 * @package App\Models
 * @version September 30, 2020, 4:22 am UTC
 *
 * @property string $name
 * @property string $description
 * @property string $rewards
 * @property string $congratulatory_message
 * @property string $terget_no_refferals
 * @property string $point_per_refferal
 */
class RefLevel extends Model
{
    use SoftDeletes;

    public $table = 'ref_levels';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'description',
        'rewards',
        'congratulatory_message',
        'terget_no_refferals',
        'point_per_refferal'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'description' => 'string',
        'rewards' => 'string',
        'congratulatory_message' => 'string',
        'terget_no_refferals' => 'string',
        'point_per_refferal' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required|string|max:255',
        'description' => 'nullable|string',
        'rewards' => 'nullable|string|max:255',
        'congratulatory_message' => 'nullable|string|max:255',
        'terget_no_refferals' => 'nullable|string|max:255',
        'point_per_refferal' => 'nullable|string|max:255',
        'deleted_at' => 'nullable',
        'created_at' => 'nullable',
        'updated_at' => 'nullable'
    ];

    
}

app/Http/Controllers/RefLevelController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRefLevelRequest;
use App\Http\Requests\UpdateRefLevelRequest;
use App\Repositories\RefLevelRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class RefLevelController extends AppBaseController
{
    /** @var  RefLevelRepository */
    private $refLevelRepository;

    public function __construct(RefLevelRepository $refLevelRepo)
    {
        $this->refLevelRepository = $refLevelRepo;
    }

    /**
     * Display a listing of the RefLevel.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $refLevels = $this->refLevelRepository->all();

        return view('ref_levels.index')
            ->with('refLevels', $refLevels);
    }

    /**
     * Show the form for creating a new RefLevel.
     *
     * @return Response
     */
    public function create()
    {
        return view('ref_levels.create');
    }

    /**
     * Store a newly created RefLevel in storage.
     *
     * @param CreateRefLevelRequest $request
     *
     * @return Response
     */
    public function store(CreateRefLevelRequest $request)
    {
        $input = $request->all();

        $refLevel = $this->refLevelRepository->create($input);

        Flash::success('Ref Level saved successfully.');

        return redirect(route('refLevels.index'));
    }

    /**
     * Display the specified RefLevel.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $refLevel = $this->refLevelRepository->find($id);

        if (empty($refLevel)) {
            Flash::error('Ref Level not found');

            return redirect(route('refLevels.index'));
        }

        return view('ref_levels.show')->with('refLevel', $refLevel);
    }

    /**
     * Show the form for editing the specified RefLevel.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $refLevel = $this->refLevelRepository->find($id);

        if (empty($refLevel)) {
            Flash::error('Ref Level not found');

            return redirect(route('refLevels.index'));
        }

        return view('ref_levels.edit')->with('refLevel', $refLevel);
    }

    /**
     * Update the specified RefLevel in storage.
     *
     * @param int $id
     * @param UpdateRefLevelRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRefLevelRequest $request)
    {
        $refLevel = $this->refLevelRepository->find($id);

        if (empty($refLevel)) {
            Flash::error('Ref Level not found');

            return redirect(route('refLevels.index'));
        }

        $refLevel = $this->refLevelRepository->update($request->all(), $id);

        Flash::success('Ref Level updated successfully.');

        return redirect(route('refLevels.index'));
    }

    /**
     * Remove the specified RefLevel from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $refLevel = $this->refLevelRepository->find($id);

        if (empty($refLevel)) {
            Flash::error('Ref Level not found');

            return redirect(route('refLevels.index'));
        }

        $this->refLevelRepository->delete($id);

        Flash::success('Ref Level deleted successfully.');

        return redirect(route('refLevels.index'));
    }
}

resources/views/ref_levels/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ref Level
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'refLevels.store']) !!}

                        @include('ref_levels.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ref_levels/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ref Level
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($refLevel, ['route' => ['refLevels.update', $refLevel->id], 'method' => 'patch']) !!}

                        @include('ref_levels.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/ref_levels/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Rewards Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rewards', 'Rewards:') !!}
    {!! Form::text('rewards', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Congratulatory Message Field -->
<div class="form-group col-sm-6">
    {!! Form::label('congratulatory_message', 'Congratulatory Message:') !!}
    {!! Form::text('congratulatory_message', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Terget No Refferals Field -->
<div class="form-group col-sm-6">
    {!! Form::label('terget_no_refferals', 'Terget No Refferals:') !!}
    {!! Form::text('terget_no_refferals', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Point Per Refferal Field -->
<div class="form-group col-sm-6">
    {!! Form::label('point_per_refferal', 'Point Per Refferal:') !!}
    {!! Form::text('point_per_refferal', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('refLevels.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/ref_levels/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Ref Levels</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('refLevels.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('ref_levels.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/ref_levels/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ref Level
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('ref_levels.show_fields')
                    <a href="{{ route('refLevels.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ref_levels/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $refLevel->name }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $refLevel->description }}</p>
</div>

<!-- Rewards Field -->
<div class="form-group">
    {!! Form::label('rewards', 'Rewards:') !!}
    <p>{{ $refLevel->rewards }}</p>
</div>

<!-- Congratulatory Message Field -->
<div class="form-group">
    {!! Form::label('congratulatory_message', 'Congratulatory Message:') !!}
    <p>{{ $refLevel->congratulatory_message }}</p>
</div>

<!-- Terget No Refferals Field -->
<div class="form-group">
    {!! Form::label('terget_no_refferals', 'Terget No Refferals:') !!}
    <p>{{ $refLevel->terget_no_refferals }}</p>
</div>

<!-- Point Per Refferal Field -->
<div class="form-group">
    {!! Form::label('point_per_refferal', 'Point Per Refferal:') !!}
    <p>{{ $refLevel->point_per_refferal }}</p>
</div>

resources/views/ref_levels/table.blade.php
<div class="table-responsive">
    <table class="table" id="refLevels-table">
        <thead>
            <tr>
                <th>Name</th>
        <th>Description</th>
        <th>Rewards</th>
        <th>Congratulatory Message</th>
        <th>Terget No Refferals</th>
        <th>Point Per Refferal</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($refLevels as $refLevel)
            <tr>
                <td>{{ $refLevel->name }}</td>
            <td>{{ $refLevel->description }}</td>
            <td>{{ $refLevel->rewards }}</td>
            <td>{{ $refLevel->congratulatory_message }}</td>
            <td>{{ $refLevel->terget_no_refferals }}</td>
            <td>{{ $refLevel->point_per_refferal }}</td>
                <td>
                    {!! Form::open(['route' => ['refLevels.destroy', $refLevel->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('refLevels.show', [$refLevel->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('refLevels.edit', [$refLevel->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>